import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';

import '../models/shopping_list.dart';

/// Service for sharing and exporting shopping lists
class ShareService {
  ShareService._();

  /// Format shopping list as plain text
  static String formatAsText(ShoppingList list) {
    final buffer = StringBuffer();
    buffer.writeln(list.name);
    buffer.writeln('=' * list.name.length);
    buffer.writeln();

    final unchecked = list.items.where((i) => !i.isChecked).toList();
    final checked = list.items.where((i) => i.isChecked).toList();

    if (unchecked.isNotEmpty) {
      buffer.writeln('To Buy:');
      for (final item in unchecked) {
        buffer.writeln('[ ] ${item.displayString}');
      }
    }

    if (checked.isNotEmpty) {
      if (unchecked.isNotEmpty) buffer.writeln();
      buffer.writeln('Completed:');
      for (final item in checked) {
        buffer.writeln('[x] ${item.displayString}');
      }
    }

    buffer.writeln();
    buffer.writeln('Generated by Recipe2Order');

    return buffer.toString();
  }

  /// Format as simple list (no checkboxes)
  static String formatAsSimpleList(ShoppingList list) {
    final buffer = StringBuffer();
    buffer.writeln(list.name);
    buffer.writeln();

    for (final item in list.items.where((i) => !i.isChecked)) {
      buffer.writeln('- ${item.displayString}');
    }

    return buffer.toString();
  }

  /// Share shopping list via system share sheet
  static Future<void> shareList(ShoppingList list) async {
    final text = formatAsText(list);
    await Share.share(text, subject: list.name);
  }

  /// Copy shopping list to clipboard
  static Future<void> copyToClipboard(ShoppingList list) async {
    final text = formatAsText(list);
    await Clipboard.setData(ClipboardData(text: text));
  }
}
